import React from 'react';
import { CircleStackIcon, ArrowRightIcon } from '@heroicons/react/24/outline';

export default function LandingPage() {
  return (
    <div className="min-h-screen w-full font-sans">
      {/* ── 1. HERO ── */}
      {/*
        Background: the Figma design uses a very-low-opacity aerial landscape image
        generated by a plugin. To replicate it:
          1. Export that layer from Figma as a PNG (e.g. hero-bg.png) → place in src/assets/
          2. Replace the inline style below with:
             style={{ backgroundImage: 'url(/src/assets/hero-bg.png)', backgroundSize: 'cover', backgroundPosition: 'center' }}
          Until then, a light radial gradient approximates the wash.
      */}
      <section
        id="hero"
        className="relative overflow-hidden bg-white py-28 text-center"
      >
        <div className="relative z-10 mx-auto max-w-[1160px] px-6">
          {/* Eyebrow */}
          <p className="text-label-sm text-content-tertiary mb-6 uppercase">
            Health Economics Financing &amp; Transparency Initiative
          </p>

          {/* Headline */}
          <h1 className="text-core-black mx-auto mb-6 max-w-4xl font-serif text-5xl leading-tight font-bold tracking-tight md:text-6xl">
            Fostering <span className="text-blue-400 italic">ownership</span>
            <br />
            <span className="text-blue-400 italic">transparency</span> in
            <br />
            health care.
          </h1>

          {/* Subtitle */}
          <p className="text-heading-xs text-content-secondary mb-4">
            Ownership, financial, and quality data for every certified nursing
            home in the U.S.&nbsp; Built to support informed decisions and
            stronger accountability.
          </p>

          {/* Attribution */}
          <p className="text-paragraph-base text-content-secondary mb-10">
            Led by{' '}
            {/* An initiative of{' '}
            <a
              href="https://weill.cornell.edu"
              className="text-blue-500 underline hover:text-blue-600"
              target="_blank"
              rel="noreferrer"
            >
              Weill Cornell Medical College
            </a>
            , led by{' '} */}
            <a
              href="https://vivo.weill.cornell.edu/display/cwid-rtb2003"
              className="text-blue-700 underline hover:text-blue-600"
              target="_blank"
              rel="noreferrer"
            >
              Dr. Robert Tyler Braun
            </a>
            , assistant professor of population health sciences
          </p>

          {/* CTA button */}
          <a
            href="/facilities"
            className="inline-flex items-center gap-3 rounded-xl bg-gray-900 px-6 py-4 text-white shadow-lg transition hover:bg-gray-800"
          >
            <CircleStackIcon className="h-6 w-6 shrink-0 text-blue-400" />
            <span className="text-left">
              <span className="block text-sm leading-tight font-semibold">
                Explore the HEFTI Platform
              </span>
              <span className="block text-xs text-gray-400">
                15,000+ facilities &amp; 51,000+ owners
              </span>
            </span>
            <ArrowRightIcon className="h-4 w-4 shrink-0 text-gray-400" />
          </a>
        </div>
      </section>

      {/* ── 2. STATS BAR ── */}
      <section id="stats" className="bg-background-inverse-primary py-12">
        {/* 15,000 / 51,000 / 139,000 / 50 */}
      </section>

      {/* ── 3. FEATURES GRID ── */}
      <section id="features" className="bg-background-primary py-20">
        {/* "Everything you need to understand a facility at a glance" + 6 cards */}
      </section>

      {/* ── 4. CTA / Q&A ── */}
      <section id="cta" className="bg-background-secondary py-20">
        {/* "Ask hard questions. Get direct answers." */}
      </section>

      {/* ── 5. RESEARCH ── */}
      <section id="research" className="bg-background-primary py-20">
        {/* "Rigorous research. Accessible data." */}
      </section>
    </div>
  );
}
