import React from 'react';
import PropTypes from 'prop-types';
import { Heading } from '../../atom/heading';
import StatsCard from '../statsCard';
import ListContainer, {
  ListContainerGrid,
  ListContainerDivider,
} from '../../organism/ListContainer';
import { AiSummaryCard, DeficiencyReportItem } from '../listContainerContent';
import FacilitiesDeficiencyBurden from '../../organism/facilitiesDeficiencyBurden';
import EntityDeficiencyBurden from '../../organism/entityDeficiencyBurden';
import { ErrorBanner, NoDataBanner } from '../../atom/errorBanner';
import {
  buildFacilityDeficienciesStats,
  buildFacilityPenaltiesStats,
  buildOwnerDeficienciesStats,
  buildOwnerPenaltiesStats,
  buildStateDeficienciesStats,
  buildStatePenaltiesStats,
} from '../../../../lib/deficienciesMetrics';
import { mapInspectionReports } from '../../../../lib/inspectionReports';

/**
 * Deficiencies & Penalties tab content.
 *
 * Responsibilities:
 * - Builds deficiency and penalty stat groups from the provided data source
 * - Switches between facility, state, and owner metric builders based on status
 * - Renders each group using ListContainer + ListContainerGrid + StatsCard
 */

/* Metric builders per subject type — each status maps its deficiency/penalty
   groups to the matching lib builder. Owner builders take only `metricsSource`
   and harmlessly ignore the benchmarks argument, so builders call uniformly.
   Unknown statuses fall back to facility (the original default). */
const STATS_BUILDERS = {
  facility: {
    deficiencies: buildFacilityDeficienciesStats,
    penalties: buildFacilityPenaltiesStats,
  },
  state: {
    deficiencies: buildStateDeficienciesStats,
    penalties: buildStatePenaltiesStats,
  },
  owner: {
    deficiencies: buildOwnerDeficienciesStats,
    penalties: buildOwnerPenaltiesStats,
  },
};

// Mock AI summary until the backend exposes it as a field on the profile. Same
// content across facility, owner, and state for now.
const PLACEHOLDER_AI_SUMMARY = {
  title: 'AI Summary',
  body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
  subtitle:
    'Generated by HEFTI AI · AI can make mistakes · Please verify responses',
};

export default function DeficienciesTab({
  metricsSource,
  status,
  nationalBenchmarks,
  facilities,
  facilitiesError,
  chains,
  individualOwners,
}) {
  // Pick the builder set for this subject type (facility is the default fallback).
  const builders = STATS_BUILDERS[status] ?? STATS_BUILDERS.facility;

  const deficienciesStats = builders.deficiencies(
    metricsSource,
    nationalBenchmarks,
  );
  const penaltiesStats = builders.penalties(metricsSource, nationalBenchmarks);
  const inspectionReports = mapInspectionReports(
    metricsSource?.inspection_reports,
  );

  /* Both owner and state render the "Deficiencies by Facility" table. Owner
     ranks its linked facilities (embedded in the payload); state ranks the
     facilities fetched for it and passed in as `facilities`. */
  let burdenFacilities = [];
  if (status === 'owner') {
    burdenFacilities =
      metricsSource?.facility_ownership_links?.map((link) => link.facility) ??
      [];
  } else if (status === 'state') {
    burdenFacilities = facilities ?? [];
  }

  return (
    <section>
      {status === 'owner' && (
        <div className="pt-8">
          <p className="text-paragraph-lg">
            Scores represent the{' '}
            <span className="font-bold">weighted average </span>
            across all facilities under this owner&apos;s management.
          </p>
        </div>
      )}
      <div className="my-8">
        <div>
          <Heading level={3} className="text-heading-sm mt-8 mb-4 font-bold">
            Deficiencies from Inspection Reports
          </Heading>
          <div className="mt-4 grid grid-cols-1 gap-4 md:grid-cols-2">
            <div className="flex flex-col gap-4">
              {deficienciesStats.map((item, i) => (
                <StatsCard key={item.key + i} item={item} />
              ))}
            </div>
            <AiSummaryCard item={PLACEHOLDER_AI_SUMMARY} />
          </div>
          {status === 'owner' || status === 'state' ? (
            <>
              {status === 'state' && facilitiesError ? (
                <ErrorBanner
                  title="Failed to load facility deficiencies"
                  message={`${facilitiesError} Try refreshing the page.`}
                />
              ) : (
                <FacilitiesDeficiencyBurden
                  facilities={burdenFacilities}
                  nationalBenchmarks={nationalBenchmarks}
                  showOwner={status === 'state'}
                  viewAllHref={
                    status === 'state' && metricsSource?.state
                      ? `/facilities?state=${encodeURIComponent(metricsSource.state)}`
                      : undefined
                  }
                />
              )}
              {status === 'state' && (
                <>
                  <EntityDeficiencyBurden
                    heading="Deficiencies by Chain"
                    nameHeader="Chain"
                    entities={chains}
                    nationalBenchmarks={nationalBenchmarks}
                    stateAbbr={metricsSource?.state}
                    linkKind="chain"
                  />
                  <EntityDeficiencyBurden
                    heading="Deficiencies by Individual Owner"
                    nameHeader="Owner"
                    entities={individualOwners}
                    nationalBenchmarks={nationalBenchmarks}
                    stateAbbr={metricsSource?.state}
                    linkKind="owner"
                  />
                </>
              )}
            </>
          ) : (
            <div className="py-4">
              {inspectionReports.length > 0 ? (
                <ListContainer
                  items={inspectionReports}
                  LayoutSelector={ListContainerDivider}
                  ListContent={DeficiencyReportItem}
                />
              ) : (
                <NoDataBanner
                  title="No inspection reports on file"
                  message="CMS Care Compare inspection PDFs have not been linked to this facility."
                />
              )}
            </div>
          )}
        </div>

        <div className="pb-8">
          <Heading level={3} className="text-heading-sm mt-8 mb-4 font-bold">
            Penalties
          </Heading>
          <ListContainer
            items={penaltiesStats}
            LayoutSelector={ListContainerGrid}
            ListContent={StatsCard}
            layoutProps={{ cols: status === 'owner' ? 2 : 3 }}
          />
        </div>
      </div>
    </section>
  );
}

DeficienciesTab.propTypes = {
  metricsSource: PropTypes.object,
  status: PropTypes.oneOf(['facility', 'owner', 'state']),
  nationalBenchmarks: PropTypes.object,
  facilities: PropTypes.arrayOf(PropTypes.object),
  facilitiesError: PropTypes.string,
  chains: PropTypes.arrayOf(PropTypes.object),
  individualOwners: PropTypes.arrayOf(PropTypes.object),
};
