name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Install dependencies and prune dev
        working-directory: hefti-data-api
        run: |
          npm prune --omit=dev

      - name: Build deployment package
        run: |
          mkdir -p hefti-data-api-prod
          cp hefti-data-api/index.js hefti-data-api-prod/
          cp hefti-data-api/package.json hefti-data-api-prod/
          cp -r hefti-data-api/prisma hefti-data-api-prod/
          cp -r hefti-data-api/node_modules hefti-data-api-prod/
          cd hefti-data-api-prod
          zip -r ../lambda.zip . > /dev/null

      - name: Upload ZIP to S3
        run: |
          aws s3 cp lambda.zip s3://hefti-lambda/lambda.zip

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name hefti-data-api \
            --s3-bucket hefti-lambda \
            --s3-key lambda.zip